import React, { useState } from 'react';
import { X, Copy, Download, FileCode, MessageSquare, Check } from 'lucide-react';
import { AnalysisResult, Language, SmartDocument, HistoryRecord } from '../types';
import { TRANSLATIONS } from '../constants';
import { Button } from './Button';

interface ShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: AnalysisResult | null;
  doc: SmartDocument | null;
  history: HistoryRecord[];
  lang: Language;
}

export const ShareModal: React.FC<ShareModalProps> = ({ isOpen, onClose, result, doc, history, lang }) => {
  const t = TRANSLATIONS[lang];
  const [copied, setCopied] = useState(false);

  if (!isOpen || !result || !doc) return null;

  // Generate Text Summary
  const generateSummary = () => {
    const changesList = result.changes.map(c => `- [${c.type}] ${c.title}`).join('\n');
    return `🚀 **${doc.title || 'Update'}** v${result.version}
📅 ${new Date().toLocaleDateString()}
📝 ${result.summary}

**Changes:**
${changesList}

*Generated by SmartDiff*`;
  };

  const summaryText = generateSummary();

  const handleCopy = () => {
    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadHtml = () => {
    // Filter relevant history for the generated report
    // If we have a doc history passed in, use it. Otherwise fallback to current result.
    let historyData = history.length > 0 
        ? history 
        : [{ 
            id: 'current', 
            version: result.version, 
            timestamp: Date.now(), 
            fullContent: doc.v2, 
            summary: result.summary, 
            docTitle: doc.title 
          }];

    // Ensure current version is in the list if not saved yet (edge case)
    const isCurrentSaved = historyData.some(h => h.version === result.version);
    if (!isCurrentSaved) {
        historyData = [{
            id: 'current-unsaved',
            version: result.version,
            timestamp: Date.now(),
            fullContent: doc.v2,
            summary: result.summary,
            docTitle: doc.title
        }, ...historyData];
    }

    // Sort history for the app (descending time)
    historyData.sort((a, b) => b.timestamp - a.timestamp);

    const safeHistoryJson = JSON.stringify(historyData).replace(/</g, '\\u003c');
    const docTitle = (doc.title || 'Document').replace(/"/g, '&quot;');
    const exportDate = new Date().toLocaleDateString();

    const htmlContent = `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${docTitle} - Interactive Report</title>
  <script src="https://cdn.tailwindcss.com?plugins=typography"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown-light.min.css">
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <script src="https://npmcdn.com/js-diff/dist/diff.min.js"></script>
  <style>
    body { background: #f5f5f7; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; }
    .markdown-body { box-sizing: border-box; min-width: 200px; max-width: 980px; margin: 0 auto; padding: 45px; background: white; border-radius: 0 0 16px 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); }
    @media (max-width: 767px) { .markdown-body { padding: 15px; } }
    .diff-added { background-color: #e6ffec; color: #1a7f37; }
    .diff-removed { background-color: #ffebe9; color: #cf222e; text-decoration: line-through; opacity: 0.8; }
    .diff-container { font-family: ui-monospace, SFMono-Regular, SF Mono, Menlo, Consolas, Liberation Mono, monospace; font-size: 12px; line-height: 1.5; background: white; border-radius: 8px; overflow: hidden; border: 1px solid #e5e7eb; }
    .diff-row { display: flex; border-bottom: 1px solid #f3f4f6; }
    .diff-num { width: 40px; padding: 4px 8px; text-align: right; color: #9ca3af; user-select: none; background: #f9fafb; border-right: 1px solid #f3f4f6; }
    .diff-content { flex: 1; padding: 4px 12px; white-space: pre-wrap; word-break: break-all; }
    .scrollbar-hide::-webkit-scrollbar { display: none; }
  </style>
</head>
<body class="h-screen flex flex-col overflow-hidden">

  <!-- Navbar -->
  <div class="bg-white/80 backdrop-blur border-b border-slate-200 px-6 py-4 flex items-center justify-between z-10 flex-shrink-0">
    <div>
      <h1 class="text-lg font-bold text-slate-900">${docTitle}</h1>
      <p class="text-xs text-slate-500">Generated: ${exportDate}</p>
    </div>
    <div class="flex items-center space-x-4">
       <div class="bg-slate-100 p-1 rounded-lg flex items-center text-sm font-medium">
          <button id="btn-reader" onclick="setView('reader')" class="px-3 py-1.5 rounded-md transition-all bg-white shadow text-slate-900">Reader</button>
          <button id="btn-diff" onclick="setView('diff')" class="px-3 py-1.5 rounded-md transition-all text-slate-500 hover:text-slate-900">Diff</button>
       </div>
    </div>
  </div>

  <!-- Controls -->
  <div class="bg-slate-50 border-b border-slate-200 px-6 py-3 flex flex-col sm:flex-row sm:items-center gap-4 z-10 flex-shrink-0">
     <div class="flex items-center space-x-2 flex-1">
        <span class="text-xs font-bold text-slate-400 uppercase w-12">Base</span>
        <select id="select-left" class="block w-full rounded-md border-0 py-1.5 text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:text-sm sm:leading-6 bg-white" onchange="render()">
           <!-- Options injected by JS -->
        </select>
     </div>
     
     <div class="text-slate-300 hidden sm:block">→</div>

     <div class="flex items-center space-x-2 flex-1">
        <span class="text-xs font-bold text-slate-400 uppercase w-12">Target</span>
        <select id="select-right" class="block w-full rounded-md border-0 py-1.5 text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 focus:ring-2 focus:ring-inset focus:ring-blue-600 sm:text-sm sm:leading-6 bg-white" onchange="render()">
           <!-- Options injected by JS -->
        </select>
     </div>
  </div>

  <!-- Content -->
  <div id="main-container" class="flex-1 overflow-y-auto bg-[#f5f5f7] p-4 sm:p-8">
     <!-- Rendered content goes here -->
  </div>

  <script>
    const historyData = ${safeHistoryJson};
    let currentView = 'reader'; // 'reader' or 'diff'

    function init() {
       const leftSelect = document.getElementById('select-left');
       const rightSelect = document.getElementById('select-right');

       historyData.forEach((rec, idx) => {
          const dateStr = new Date(rec.timestamp).toLocaleString();
          const label = \`v\${rec.version} - \${dateStr}\`;
          
          const optLeft = document.createElement('option');
          optLeft.value = idx;
          optLeft.text = label;
          leftSelect.appendChild(optLeft);

          const optRight = document.createElement('option');
          optRight.value = idx;
          optRight.text = label;
          rightSelect.appendChild(optRight);
       });

       // Default: Left = Previous (index 1), Right = Latest (index 0)
       if (historyData.length > 1) {
         leftSelect.selectedIndex = 1;
         rightSelect.selectedIndex = 0;
       } else {
         leftSelect.selectedIndex = 0;
         rightSelect.selectedIndex = 0;
       }

       render();
    }

    function setView(mode) {
       currentView = mode;
       document.getElementById('btn-reader').className = mode === 'reader' ? 'px-3 py-1.5 rounded-md transition-all bg-white shadow text-slate-900' : 'px-3 py-1.5 rounded-md transition-all text-slate-500 hover:text-slate-900';
       document.getElementById('btn-diff').className = mode === 'diff' ? 'px-3 py-1.5 rounded-md transition-all bg-white shadow text-slate-900' : 'px-3 py-1.5 rounded-md transition-all text-slate-500 hover:text-slate-900';
       render();
    }

    function render() {
       const leftIdx = document.getElementById('select-left').value;
       const rightIdx = document.getElementById('select-right').value;
       const container = document.getElementById('main-container');
       
       const leftDoc = historyData[leftIdx];
       const rightDoc = historyData[rightIdx];

       if (currentView === 'reader') {
          const html = marked.parse(rightDoc.fullContent);
          container.innerHTML = \`<div class="markdown-body">\${html}</div>\`;
       } else {
          // Diff Mode
          const diff = Diff.diffLines(leftDoc.fullContent, rightDoc.fullContent);
          let html = '<div class="max-w-5xl mx-auto diff-container">';
          let lNum = 1;
          let rNum = 1;

          diff.forEach(part => {
             const lines = part.value.replace(/\\n$/, '').split('\\n');
             const colorClass = part.added ? 'diff-added' : part.removed ? 'diff-removed' : '';
             
             lines.forEach(line => {
                html += '<div class="diff-row">';
                // Line Numbers
                html += '<div class="diff-num">';
                if (!part.added) html += (lNum++);
                html += '</div>';
                html += '<div class="diff-num">';
                if (!part.removed) html += (rNum++);
                html += '</div>';
                // Content
                html += \`<div class="diff-content \${colorClass}">\${escapeHtml(line)}</div>\`;
                html += '</div>';
             });
          });
          html += '</div>';
          container.innerHTML = html;
       }
    }

    function escapeHtml(unsafe) {
      return unsafe
         .replace(/&/g, "&amp;")
         .replace(/</g, "&lt;")
         .replace(/>/g, "&gt;")
         .replace(/"/g, "&quot;")
         .replace(/'/g, "&#039;");
    }

    init();
  </script>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${(doc.title || 'document').replace(/\s+/g, '_')}_History_Report.html`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/30 backdrop-blur-md transition-all duration-300">
      <div className="bg-white rounded-[32px] shadow-2xl w-full max-w-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-300 border border-white/50">
        <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
           <h3 className="text-lg font-bold text-slate-900">{t.shareModalTitle}</h3>
           <button onClick={onClose} className="p-2 hover:bg-slate-200 rounded-full text-slate-400 hover:text-slate-600"><X className="w-5 h-5"/></button>
        </div>

        <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
           {/* Summary Card */}
           <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 flex flex-col h-full hover:shadow-md transition-shadow">
              <div className="flex items-center mb-3 text-slate-900 font-bold text-sm uppercase tracking-wide">
                 <MessageSquare className="w-4 h-4 mr-2 text-[#0071e3]" />
                 {t.shareTabSummary}
              </div>
              <p className="text-xs text-slate-500 mb-4 min-h-[32px]">{t.shareSummaryDesc}</p>
              <div className="flex-1 bg-white border border-slate-200 rounded-xl p-3 mb-4 overflow-y-auto max-h-[150px] custom-scrollbar shadow-inner">
                 <pre className="text-[10px] text-slate-600 whitespace-pre-wrap font-mono">{summaryText}</pre>
              </div>
              <Button onClick={handleCopy} variant={copied ? "primary" : "secondary"} className="w-full justify-center">
                 {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                 {copied ? t.summaryCopied : t.btnCopySummary}
              </Button>
           </div>

           {/* HTML Report Card */}
           <div className="bg-slate-50 rounded-2xl p-5 border border-slate-200 flex flex-col h-full hover:shadow-md transition-shadow">
              <div className="flex items-center mb-3 text-slate-900 font-bold text-sm uppercase tracking-wide">
                 <FileCode className="w-4 h-4 mr-2 text-[#0071e3]" />
                 {t.shareTabHtml}
              </div>
              <p className="text-xs text-slate-500 mb-4 min-h-[32px]">{t.shareHtmlDesc}</p>
              <div className="flex-1 flex items-center justify-center mb-4 opacity-40">
                 <FileCode className="w-20 h-20 text-slate-300" />
              </div>
              <Button onClick={handleDownloadHtml} className="w-full justify-center mt-auto">
                 <Download className="w-4 h-4 mr-2" />
                 {t.btnDownloadHtml}
              </Button>
           </div>
        </div>
      </div>
    </div>
  );
};